baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Elasticsearch 搜索开发实战"
theme = "hugo-theme-learn"
# themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
  # themeVariant = "green"
  editURL = "https://github.com/medcl/book-elastic-search-in-action/edit/master/content/"
  description = "Elasticsearch 搜索开发实战"
  author = "Medcl"
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = true
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = ""

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30

[Languages]
[Languages.en]
title = " Elastic 搜索开发实战"
weight = 1
languageName = "简体中文"
